---
development:
  cloud_name: hnoeixvof
  api_key: '166531779459732'
  api_secret: cAaToVaz_MLPo7VMtVBYkLBFviU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hnoeixvof
  api_key: '166531779459732'
  api_secret: cAaToVaz_MLPo7VMtVBYkLBFviU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hnoeixvof
  api_key: '166531779459732'
  api_secret: cAaToVaz_MLPo7VMtVBYkLBFviU
  enhance_image_tag: true
  static_image_support: false
